### ISSUE TITLE
mirrors-qa CD

### ISSUE THREAD

**Issue by rgaudin** [kiwix/operations#249]
It seems (seen that several times) that CD deployment always creates a new `api-deployment-*` (pending) but the previous one is still running.

**Comment by benoit74** [comment]
This is linked to the deployment [strategy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy). By default, it is a rolling update. You can specify `Recreate` if needed

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
```
